import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import type { Ward } from '@/types';

type View = 'signin' | 'register';

export default function Login() {
  const { isSetup, isLocked, firstName: savedFirst, lastName: savedLast, setup, login } = useAuth();

  // If setup is done, show PIN login; otherwise show setup form
  // isLocked means auto-locked — same PIN entry but with "Welcome back"

  // View toggle (only relevant for first-run)
  const [view, setView] = useState<View>('signin');

  // Setup form state
  const [trustName, setTrustName] = useState('');
  const [unitName, setUnitName] = useState('');
  const [wardName, setWardName] = useState('');
  const [managerEmail, setManagerEmail] = useState('');
  const [setupFirstName, setSetupFirstName] = useState('');
  const [setupLastName, setSetupLastName] = useState('');
  const [setupPin, setSetupPin] = useState('');
  const [confirmPin, setConfirmPin] = useState('');
  const [generatedCode, setGeneratedCode] = useState<string | null>(null);
  const [setupError, setSetupError] = useState('');

  // PIN login state
  const [pin, setPin] = useState('');
  const [pinError, setPinError] = useState('');
  const [loading, setLoading] = useState(false);

  // ─── Setup handler ─────────────────────────────────────────────

  const handleSetup = async (e: React.FormEvent) => {
    e.preventDefault();
    setSetupError('');

    if (setupPin.length < 6) {
      setSetupError('PIN must be at least 6 digits');
      return;
    }
    if (setupPin !== confirmPin) {
      setSetupError('PINs do not match');
      return;
    }

    setLoading(true);
    try {
      const ward: Ward = {
        id: `w${Date.now()}`,
        name: wardName,
        unitName,
        trustName,
        adminEmail: managerEmail,
        wardCode: '', // will be generated by setup()
        subscriptionStatus: 'trial',
        cycleStartDate: new Date().toISOString(),
        createdAt: new Date().toISOString(),
      };

      const code = await setup(ward, setupFirstName, setupLastName, setupPin);
      setGeneratedCode(code);
    } catch {
      setSetupError('Setup failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ─── PIN login handler ─────────────────────────────────────────

  const handlePinLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setPinError('');
    setLoading(true);

    try {
      const success = await login(pin);
      if (!success) {
        setPinError('Incorrect PIN');
        setPin('');
      }
    } catch {
      setPinError('Login failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ─── PIN Login View (returning user or locked) ─────────────────

  if (isSetup) {
    return (
      <div className="relative flex min-h-screen w-full flex-col items-center justify-center overflow-hidden bg-slate-50 px-4 py-8">
        <EcgBackground />

        <div className="relative z-10 mb-8 flex flex-col items-center">
          <LogoIcon />
          <h1 className="text-2xl font-semibold tracking-tight text-[#0B1E36] sm:text-3xl">
            NEWS<span className="text-[#00AEEF]">2</span> Digital Chart
          </h1>
          <p className="mt-1 text-sm text-slate-400">
            {isLocked ? 'Session locked' : 'Ward observation tracking'}
          </p>
        </div>

        <div className="relative z-10 w-full max-w-sm">
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
            <div className="mb-5 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#0B1E36]">
                <svg className="h-5 w-5 text-[#00AEEF]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="3" y="11" width="18" height="11" rx="2" ry="2" />
                  <path d="M7 11V7a5 5 0 0110 0v4" />
                </svg>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-[#0B1E36]">
                  Welcome back, {savedFirst}
                </h2>
                <p className="text-xs text-slate-400">Enter your PIN to unlock</p>
              </div>
            </div>

            <form onSubmit={handlePinLogin} className="space-y-4">
              <div>
                <label htmlFor="pin" className="mb-1.5 block text-xs font-medium text-slate-500">
                  PIN
                </label>
                <input
                  id="pin"
                  type="password"
                  inputMode="numeric"
                  required
                  autoFocus
                  value={pin}
                  onChange={(e) => {
                    setPin(e.target.value.replace(/\D/g, ''));
                    setPinError('');
                  }}
                  placeholder="Enter your PIN"
                  className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-center text-2xl font-bold tracking-[0.3em] text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-[#00AEEF] focus:bg-white focus:ring-1 focus:ring-[#00AEEF]"
                />
                {pinError && (
                  <p className="mt-1.5 text-xs font-medium text-red-500">{pinError}</p>
                )}
              </div>

              <button
                type="submit"
                disabled={loading || pin.length < 6}
                className="group mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0B1E36] py-3 text-sm font-semibold text-white transition-all hover:shadow-lg hover:shadow-slate-900/20 disabled:opacity-40"
              >
                {loading ? 'Unlocking...' : 'Unlock'}
                {!loading && (
                  <svg className="h-4 w-4 transition-transform group-hover:translate-x-0.5" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M3 10a.75.75 0 01.75-.75h10.638L10.23 5.29a.75.75 0 111.04-1.08l5.5 5.25a.75.75 0 010 1.08l-5.5 5.25a.75.75 0 11-1.04-1.08l4.158-3.96H3.75A.75.75 0 013 10z" clipRule="evenodd" />
                  </svg>
                )}
              </button>
            </form>

            <p className="mt-4 text-center text-[10px] text-slate-400">
              {savedFirst} {savedLast}
            </p>
          </div>
        </div>

        <EcgStyle />
      </div>
    );
  }

  // ─── First Run: Setup / Register view ──────────────────────────

  return (
    <div className="relative flex min-h-screen w-full flex-col items-center justify-center overflow-hidden bg-slate-50 px-4 py-8">
      <EcgBackground />

      {/* Logo + title */}
      <div className="relative z-10 mb-8 flex flex-col items-center">
        <LogoIcon />
        <h1 className="text-2xl font-semibold tracking-tight text-[#0B1E36] sm:text-3xl">
          NEWS<span className="text-[#00AEEF]">2</span> Digital Chart
        </h1>
        <p className="mt-1 text-sm text-slate-400">Ward observation tracking</p>
      </div>

      {/* Card */}
      <div className="relative z-10 w-full max-w-md">
        {/* Tab toggle */}
        {!generatedCode && (
          <div className="mb-4 flex rounded-full border border-slate-200 bg-white p-1 shadow-sm">
            <button
              onClick={() => { setView('signin'); setGeneratedCode(null); }}
              className={`flex-1 rounded-full py-2 text-sm font-medium transition ${
                view === 'signin'
                  ? 'bg-[#0B1E36] text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-600'
              }`}
            >
              Set Up Ward
            </button>
            <button
              onClick={() => { setView('register'); setGeneratedCode(null); }}
              className={`flex-1 rounded-full py-2 text-sm font-medium transition ${
                view === 'register'
                  ? 'bg-[#0B1E36] text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-600'
              }`}
            >
              About
            </button>
          </div>
        )}

        {/* Setup form */}
        {view === 'signin' && !generatedCode && (
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
            <div className="mb-5 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#00AEEF]/10">
                <svg className="h-5 w-5 text-[#00AEEF]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                  <circle cx="9" cy="7" r="4" />
                  <line x1="19" y1="8" x2="19" y2="14" /><line x1="22" y1="11" x2="16" y2="11" />
                </svg>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-[#0B1E36]">Set Up Ward</h2>
                <p className="text-xs text-slate-400">Register your ward and create a secure PIN</p>
              </div>
            </div>

            <form onSubmit={handleSetup} className="space-y-3">
              {/* Ward details */}
              <div>
                <label htmlFor="trustName" className="mb-1.5 block text-xs font-medium text-slate-500">Trust Name</label>
                <input id="trustName" type="text" required value={trustName} onChange={(e) => setTrustName(e.target.value)} placeholder="e.g. Royal London NHS Trust" className={inputClass} />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label htmlFor="unitName" className="mb-1.5 block text-xs font-medium text-slate-500">Unit Name</label>
                  <input id="unitName" type="text" required value={unitName} onChange={(e) => setUnitName(e.target.value)} placeholder="e.g. Acute Medicine" className={inputClass} />
                </div>
                <div>
                  <label htmlFor="wardName" className="mb-1.5 block text-xs font-medium text-slate-500">Ward Name</label>
                  <input id="wardName" type="text" required value={wardName} onChange={(e) => setWardName(e.target.value)} placeholder="e.g. Ward A1" className={inputClass} />
                </div>
              </div>

              <div>
                <label htmlFor="managerEmail" className="mb-1.5 block text-xs font-medium text-slate-500">Manager's Email</label>
                <input id="managerEmail" type="email" required value={managerEmail} onChange={(e) => setManagerEmail(e.target.value)} placeholder="e.g. manager@nhs.net" className={inputClass} />
              </div>

              {/* Staff name */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label htmlFor="setupFirst" className="mb-1.5 block text-xs font-medium text-slate-500">First Name</label>
                  <input id="setupFirst" type="text" required value={setupFirstName} onChange={(e) => setSetupFirstName(e.target.value)} placeholder="e.g. Sarah" className={inputClass} />
                </div>
                <div>
                  <label htmlFor="setupLast" className="mb-1.5 block text-xs font-medium text-slate-500">Surname</label>
                  <input id="setupLast" type="text" required value={setupLastName} onChange={(e) => setSetupLastName(e.target.value)} placeholder="e.g. Jones" className={inputClass} />
                </div>
              </div>

              {/* PIN creation */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label htmlFor="setupPin" className="mb-1.5 block text-xs font-medium text-slate-500">Create PIN (6+ digits)</label>
                  <input
                    id="setupPin"
                    type="password"
                    inputMode="numeric"
                    required
                    value={setupPin}
                    onChange={(e) => { setSetupPin(e.target.value.replace(/\D/g, '')); setSetupError(''); }}
                    placeholder="••••••"
                    className={inputClass}
                  />
                </div>
                <div>
                  <label htmlFor="confirmPin" className="mb-1.5 block text-xs font-medium text-slate-500">Confirm PIN</label>
                  <input
                    id="confirmPin"
                    type="password"
                    inputMode="numeric"
                    required
                    value={confirmPin}
                    onChange={(e) => { setConfirmPin(e.target.value.replace(/\D/g, '')); setSetupError(''); }}
                    placeholder="••••••"
                    className={inputClass}
                  />
                </div>
              </div>

              {setupError && (
                <p className="text-xs font-medium text-red-500">{setupError}</p>
              )}

              <button
                type="submit"
                disabled={loading}
                className="group mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0B1E36] py-3 text-sm font-semibold text-white transition-all hover:shadow-lg hover:shadow-slate-900/20 disabled:opacity-40"
              >
                {loading ? 'Setting up...' : 'Register & Get Ward Code'}
                {!loading && (
                  <svg className="h-4 w-4 transition-transform group-hover:translate-x-0.5" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M3 10a.75.75 0 01.75-.75h10.638L10.23 5.29a.75.75 0 111.04-1.08l5.5 5.25a.75.75 0 010 1.08l-5.5 5.25a.75.75 0 11-1.04-1.08l4.158-3.96H3.75A.75.75 0 013 10z" clipRule="evenodd" />
                  </svg>
                )}
              </button>
            </form>
          </div>
        )}

        {/* Success: Ward code generated */}
        {generatedCode && (
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
            <div className="text-center">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-green-50">
                <svg className="h-7 w-7 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                </svg>
              </div>
              <h2 className="mb-2 text-lg font-semibold text-[#0B1E36]">Ward Set Up!</h2>
              <p className="mb-6 text-sm text-slate-500">
                Your ward is ready. Data is encrypted and stored locally on this device.
              </p>

              <div className="mb-6 rounded-2xl border-2 border-dashed border-[#00AEEF]/30 bg-[#00AEEF]/5 p-6">
                <p className="mb-1 text-xs font-medium uppercase tracking-wider text-slate-400">Your Ward Code</p>
                <p className="text-5xl font-bold tracking-[0.3em] text-[#0B1E36]">{generatedCode}</p>
              </div>

              <div className="mb-6 rounded-xl bg-amber-50 p-3 text-left text-xs text-amber-700">
                <p className="font-semibold">Remember your PIN</p>
                <p className="mt-0.5">Your PIN is the only way to access the encrypted data on this device. It cannot be recovered.</p>
              </div>

              <p className="mb-6 text-xs text-slate-400">
                You are now signed in as <span className="font-medium text-slate-600">{setupFirstName} {setupLastName}</span>
              </p>

              {/* The user is already authenticated after setup — this just dismisses the view */}
              <p className="text-xs text-green-600 font-medium">
                Redirecting to dashboard...
              </p>
            </div>
          </div>
        )}

        {/* About panel */}
        {view === 'register' && !generatedCode && (
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
            <div className="mb-5 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#0B1E36]">
                <svg className="h-5 w-5 text-[#00AEEF]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2" />
                  <rect x="9" y="3" width="6" height="4" rx="1" />
                  <path d="M9 14l2 2 4-4" />
                </svg>
              </div>
              <div>
                <h2 className="text-lg font-semibold text-[#0B1E36]">NEWS2 Digital Chart</h2>
                <p className="text-xs text-slate-400">Secure ward observation tracking</p>
              </div>
            </div>

            <div className="space-y-3 text-sm text-slate-600">
              <div className="flex items-start gap-2">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-green-50 text-[10px] text-green-600">1</span>
                <p><span className="font-medium text-[#0B1E36]">Offline-first</span> — All data stored locally on this device. No internet required after setup.</p>
              </div>
              <div className="flex items-start gap-2">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-green-50 text-[10px] text-green-600">2</span>
                <p><span className="font-medium text-[#0B1E36]">Encrypted</span> — All clinical data is AES-256 encrypted. Only accessible with your PIN.</p>
              </div>
              <div className="flex items-start gap-2">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-green-50 text-[10px] text-green-600">3</span>
                <p><span className="font-medium text-[#0B1E36]">Auto-lock</span> — Automatically locks after 5 minutes of inactivity on shared devices.</p>
              </div>
              <div className="flex items-start gap-2">
                <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-green-50 text-[10px] text-green-600">4</span>
                <p><span className="font-medium text-[#0B1E36]">Audited</span> — All actions are logged for compliance and governance.</p>
              </div>
            </div>

            <div className="mt-6 rounded-xl bg-slate-50 p-3 text-xs text-slate-400">
              Not a certified medical device. Follow local trust policies.
            </div>
          </div>
        )}
      </div>

      <EcgStyle />
    </div>
  );
}

// ─── Shared Constants & Components ─────────────────────────────────

const inputClass = 'w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 text-sm text-slate-800 placeholder-slate-400 outline-none transition-all focus:border-[#00AEEF] focus:bg-white focus:ring-1 focus:ring-[#00AEEF]';

function LogoIcon() {
  return (
    <div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-[#0B1E36] shadow-lg">
      <svg className="h-7 w-7 text-[#00AEEF]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2" />
        <rect x="9" y="3" width="6" height="4" rx="1" />
        <path d="M9 14l2 2 4-4" />
      </svg>
    </div>
  );
}

function EcgBackground() {
  const ecgPath = "M0,100 L80,100 L100,100 L110,90 L120,100 L160,100 L175,100 L180,60 L185,160 L190,30 L195,140 L200,100 L220,100 L240,95 L260,100 L300,100 M300,100 L380,100 L400,100 L410,90 L420,100 L460,100 L475,100 L480,60 L485,160 L490,30 L495,140 L500,100 L520,100 L540,95 L560,100 L600,100 M600,100 L680,100 L700,100 L710,90 L720,100 L760,100 L775,100 L780,60 L785,160 L790,30 L795,140 L800,100 L820,100 L840,95 L860,100 L900,100 M900,100 L980,100 L1000,100 L1010,90 L1020,100 L1060,100 L1075,100 L1080,60 L1085,160 L1090,30 L1095,140 L1100,100 L1120,100 L1140,95 L1160,100 L1200,100 M1200,100 L1280,100 L1300,100 L1310,90 L1320,100 L1360,100 L1375,100 L1380,60 L1385,160 L1390,30 L1395,140 L1400,100 L1420,100 L1440,95 L1460,100 L1500,100 M1500,100 L1580,100 L1600,100 L1610,90 L1620,100 L1660,100 L1675,100 L1680,60 L1685,160 L1690,30 L1695,140 L1700,100 L1720,100 L1740,95 L1760,100 L1800,100 M1800,100 L1880,100 L1900,100 L1910,90 L1920,100 L1960,100 L1975,100 L1980,60 L1985,160 L1990,30 L1995,140 L2000,100 L2020,100 L2040,95 L2060,100 L2100,100 M2100,100 L2180,100 L2200,100 L2210,90 L2220,100 L2260,100 L2275,100 L2280,60 L2285,160 L2290,30 L2295,140 L2300,100 L2320,100 L2340,95 L2360,100 L2400,100";

  return (
    <div className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden opacity-[0.04]">
      <svg
        viewBox="0 0 2400 200"
        className="absolute w-[300%] max-w-none"
        preserveAspectRatio="none"
        style={{ animation: 'ecg-scroll 8s linear infinite' }}
      >
        <path d={ecgPath} fill="none" stroke="#0B1E36" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    </div>
  );
}

function EcgStyle() {
  return (
    <style>{`
      @keyframes ecg-scroll {
        0% { transform: translateX(0); }
        100% { transform: translateX(-33.33%); }
      }
    `}</style>
  );
}
